### ISSUE TITLE
Curious question

### ISSUE THREAD

**Issue by JeanTheFungle** [SnesFX/Mogus2018#1]
hey @TyDevX hey this first time i see this repo and i like is among us 2018 it work servers and bug fixed because i have annother on2019 but its buggy contact me on disc : jeanamongus

**Comment by JeanAU** [comment]
- [ ] i recommand to update this project to 2020.3.7f1 unity version

**Comment by TyDevX** [comment]
> * [ ]  i recommand to update this project to 2020.3.7f1 unity version

My laptop cannot handle Unity 2020 without lag 💀 

also yeah I'll add you
