### ISSUE TITLE
Shaders & I Can HELP!!!

### ISSUE THREAD

**Issue by Pietrodjaowjao** [SnesFX/Mogus2018#2]
i see that you are using dummy shaders, i have decompiled among us 2019.8.16s, i can help you if you want.

**Comment by Pietrodjaowjao** [comment]
all the shaders of mine are working correctly

**Comment by Pietrodjaowjao** [comment]
my discord is pietro420, i'm also friend of JeanAU

**Comment by JeanAU** [comment]
> my discord is pietro420, i'm also friend of JeanAU

yes he my friend he is a best among us modder he made many mods for among us and many ohter mods soon
